version: '3.9'
services:
    client:
        build:
            context: ./client
            args:
                VITE_SERVER_URL: ${VITE_SERVER_URL}
                VITE_ENCRYPTION_KEY: ${VITE_ENCRYPTION_KEY}
                CLIENT_PORT: ${CLIENT_PORT}
        restart: always
        ports:
            - ${ROOT_PORT}:80
        depends_on:
            - server
    server:
        build: ./server
        restart: always
        environment:
            SERVER_PORT: ${SERVER_PORT}
            SERVER_DATABASE_ENCRYPTION_KEY: ${SERVER_DATABASE_ENCRYPTION_KEY}
            SERVER_DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
        depends_on:
            - database
    database:
        image: postgres
        restart: always
        volumes:
            - postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
volumes:
    postgres:
